clic.adoc

- Change occurrences of clicfg to cliccfg
Perhaps keep this PR open if I find any other minor editorial fixes...

Minor edits

---

clic.adoc

Change shoudl to should.

---

clic.adoc

Spec update for issue #49, #79 (formerly #57 -3)

Update clic.adoc - Spec update for issue #49, #79 (formerly #57 -3) - downplay M/S/U memory map requirements

---

clic.adoc

recreating a pull because pull #130 had merge issues.

attempt at a DTS entry for CLIC for issue #91

---

clic.adoc

update for issue #107.  still need to add more references.

adding bibliography section

---

clic.adoc

for issue #162, specify the clicintie bit as bit 0 with same wording as clicintip.

specify clicintie bit

---

clic.adoc

moved default value of clicintattr.mode to the reset chapter

moving all reset statements to reset section

---

clic.adoc

for issue #180, change references from processor to hart

change processor to hart in document

---

clic.adoc

adding arch string for CLIC to spec title and initial background chapter.  tried to match priv spec wording for other extensions.  for issue #109

for issue #109

---

clic.adoc

clarify how changes to mtvec affect s/utvec

xtvec clarification for issue #45

---

clic.adoc

adds note to resolve reserved address space question in issue #220.

pull for issue #220

---

clic.adoc

pull for issues:
#275 -allows omitting scheme in U/M system with no N-ext,
#274 - tried to more closely follow riscv sail model.  

inhv pseudo code clarification attempt

---

clic.adoc

pull for #294 - move xintstatus addresses

---

clic.adoc

pull for issue #293, separate cliccfg per priv mode

pull for issue #293, separate cliccfg per priv mode

---

clic.adoc

removed requirement of 4k boundary base address.  made it a recommendation.  should the wording be updated to reflect platform may mandate?

mem map clarification for issue #304

---

clic.adoc

update for issue #311 - nlbits

---

clic.adoc

added explicit text detailing CLIC fields added to RNMI CSR mncause for issue #320

RMNI text clarification for issue #320

---

clic.adoc

changed text that says "prevents" to "helps software avoid" for issue #334

text update for question 1 of issue #334

---

clic.adoc

clean-up of pseudo code For issue #358, #357.

pseudo-code update of mret with inhv

---

clic.adoc

for issue #355, clic and RNMI are orthogonal. updated clic text.

correct clic/rnmi interaction

---

src/clic.adoc

fix for #427.  clarify clearing the low bit(s)

text update for #427

---

src/clic.adoc

504 exceptions should be vectored with hw vectoring

---

src/aclic.adoc

Summarizing the dependencies in a table

intro: cleaning up extension dependencies
