clic.adoc

For hardware vectoring access exceptions, both {tval} and {epc} holds the faulting address.  Spec update for issues #111 and #105 (option 2 reasoning)

Update clic.adoc-For hardware vectoring access exceptions, both {tval} and {epc} holds the faulting address. Spec update for issues #111 and #105

---

clic.adoc

Add comparison of CLIC to Advanced Interrupt Architecture in background/motivation section.

Update clic.adoc - add comparison of CLIC to Advanced Interrupt Architecture

---

clic.adoc

spec update for issue #26 - change description to no longer defining micro-architectural behavior of xINHV.   With this pull and pull #131 hopefully close this issue.

Update clic.adoc for issue #26 - modify wording that defined micro-architectural behavior of xINHV

---

clic.adoc

closing pull #127 due to typos.  moved CLIC Reset Behavior to section 6 instead of section 4.  Added xintstatus reset value.

spec clarification based on issue #47 - CLIC reset behavior

---

clic.adoc

Spec update for issues #117, #125 Change text to match table in (Specifying Interrupt Privilege Mode).  in M/S/U system, if nmbits ==1 , selects between M-mode and S-mode.

Update clic.adoc for issues #117, #125 change text to match table in M/S/U system if nmbits==1

---

test-plan-clic.adoc

summary of method of creating deterministic architectural tests that can be compared to SAIL.  list of implementation parameters.  Initial list of tests

Creation of test-plan-clic.adoc as a starting point for architectural test discussion

---

clic.adoc

specified mtvec.mode controls CLIC mode as part of issue #45

additional spec change for issue #45

---

clic.adoc

reverting pull request #129 to add back s-mode and u-mode regions and add clarification that the accessibility of s-mode and u-mode interrupts can be implemented with address range aliasing.

CLIC memory mapped privilege region clarification for issue #156

---

clic.adoc

proposal to simplify clicintctl to either represent interrupt levels (used to determine preemption for nesting interrupts) or priorities (does not affect preemption).  Reduced spec changes by describing cliccfg.nlbits as only supporting 0 or 8 and other values are reserved.  See #167

clicintctl simplification

---

clic.adoc

Clarify that all CSR instructions may be used and what happens when they are.
Change overly restrictive wording on when pending is cleared
Add comments to pseudo-code for how it changes for different CSR instructions and different privileges.

Clarify xnxti description

---

clic.adoc

for issue #188 - clarify writes to xcause.mpp/mpie fields.  Adding a note to with similar language used in the privilege specification in describing read/write accesses to sstatus/mstatus fields.

for issue #188 - clarify writes to xcause.mpp/mpie fields

---

clic.adoc

Pull for issue #195.  We will discuss this wording in our next TG meeting.  I tried to clarify that the WFI section of the spec only specifies when the hart must resume, not whether an interrupt is taken or not.

attempt to clarify WFI for issue #195

---

clic.adoc

updated text to match Zc extension table jump fault handling text.  (issue #191)
https://github.com/riscv/riscv-code-size-reduction/edit/main/Zc-specification/tablejump.adoc
updated changes to epc CSR section to mention the hardware vectoring faulting address (issue #224) 
also updated text to provide for mtval hardwired to 0 option as specified in the privileged spec. (issue #223)

change vector table read to only require execute permissions

---

clic.adoc

make explicit that exceptions update xcause.xpil.  For issue #235.   Changed "exception" to "trap" to match priv spec wording.

xcause field behavior on exceptions/traps clarification

---

clic.adoc

Pull to fix parameter value ranges for NUM_INTERRUPT and CLICMTVECALIGN for issues #212 and #213

CLIC parameter value ranges fix

---

clic.adoc

Added WARL and restriction on which bits need to be implemented for xintthresh

allow implementing less than 8 bits for xintthresh

---

clic.adoc

Pull for issue #245 the table in section 5.4 lists xtvec.mode as xtvec bits 5:0, and clic mode is defined as 00001?.  Updating the above text to match.

updating text to match table for issue #245

---

clic.adoc

tried to write pseudo SAIL code to make explicit which xinhv and which xepc is used on xRET.  This also shows xRET perform the same operation regardless of the mode in which they are executed.

pull for issue #197

---

clic.adoc

instead of redefining xtvec.mode as 5:0 of xtvec, created a new field in xtvec called alignment which is bits [5:2].

pull for #248/249

---

clic.adoc

reserving use of uimm bits in xnxti for future use.

pull for issue #100

---

clic.adoc

added 4KiB base addr requirement.  specified 8b, 16b, 32b are atomic.  specified 64 can be split in 32b but did not require order.  review if 64 stores require an order.

pull for #202

---

clic.adoc

defined CLINT mode and changed references from using "original" to instead refer to "CLINT mode".  Also removed some references to the "new CLIC", instead just calling it CLIC mode.

define CLINT mode as mtvec.mode = 00/01

---

clic.adoc

clarification for issue #229.  read and implicit read value of clicintattr.mode will match interrupt mode table and unchanged by writes to cliccfg.nmbits

clarify clicintattr.mode WARL behavior

---

clic.adoc

for issue #219 
moved csip to id 16 to not conflict with AIA ordering.  added mention that it might be used for context switching.

csip interrupt ordering clarification for issue #219

---

clic.adoc

clarification for issue #191 - use a non-normative comment to help explain table permissions settings for one or both of hardware and software vectoring.

software vectoring clarification for #191

---

clic.adoc

clarification of behavior breakpoints on hw vector table reads.

clarification for issues #239, #228

---

clic.adoc

For issue #255 adding text to clearly define how to set CLINT mode and how xtvec.mode bit 1 WARL behaves in lower privilege modes.  

clearly define CLINT mode

---

clic.adoc

text clarification for #267.  change "implemenation ... is not defined" to ... is implementation-defined" to better match language in priv spec.

text clarification for #267

---

clic.adoc

text cleanup for issue #271.  xRET pseudo-code cleanup for issue #272.  setting ucause_inhv to 0 in xRET pseudo-code when u-mode not implemented or user-interrupts not implemented.  using sail syntax from: https://github.com/riscv/sail-riscv/blob/master/model/riscv_insts_next.sail

change inhv to xinhv

---

clic.adoc

text refers to table load but better to use the term fetch since it uses fetch permissions. clarify horizontal note.

#275 clarify hwvector text

---

clic.adoc

moved mclicbase, xclicbase, nvbits, clicinfo to parameters section.   For issue #282 

moved mclicbase, nvbits, clicinfo to parameters section

---

clic.adoc

for issue #280   updating text to only define CSRRSI and CSRRCI similar to how xscratchcsw text was updated.

updated nxti CSR access types, other uses reserved

---

clic.adoc

for issue #255  
clarify that since only all clic or all clint is supported, changing from clic to clint clears all xinhv and xpil fields to be cleared.

clic xcause clearing clarification

---

clic.adoc

reorganization for issue #75 and issue #160 - reordered text into 5 extensions, smclic, ssclic, suclic, smclicshv, smclicconfig. No functional changes intended.

reorder text to split into different clic extensions.

---

clic.adoc

Fix for issue #298 - removed redundant note (cut and paste error).

typo fix - repeated text fix for issue #298

---

clic.adoc

remove optional wording on xnxti and xscratchcsw/xscratchcswl CSRs.  if clicinttrig is not implemented, appear as hard-wired zeros.

make clicinttrig, xnxti/xscratchcsw/xscratchcswl non-optional

---

clic.adoc

fix for issue #305
removed xedeleg references,  added note that CLIC does not change exception scheme. removed references to sideleg, uideleg. 
added "if it exists" qualification to xideleg.

fix for issue #305 concerning xideleg and xedeleg text

---

clic.adoc

For issue #295,  a new proposal to have hardware automatically clear *intthresh when going to a lower mode via SRET and MRET. This is similar to the mstatus.mprv change in priv 1.12. This avoids the issue and also removes a potential source of bugs.

clear xintthresh on changes to lower priv modes

---

clic.adoc

pull #310 added text that clears xintthresh going to lower priv with MRET, SRET.  Adding equivalent text for when debug spec DRET goes to lower priv.

for issue #295, include mention of xintthresh clearing and DRET

---

clic.adoc

pull for #318 - use "zero" instead of x0 in assembly examples

pull for #318 - use "zero" instead of x0 in assembly examples

---

clic.adoc

added a comment that the example code doesn't account for presence of f or v registers for issue #317

added note for issue #317

---

clic.adoc

fix for issue #321, change text that says intthresh is cleared or zero-ed to intthresh is set to the lowest support value.

intthresh clearing text update for issue #321

---

clic.adoc

text updates for issue #322
stated xcliccfg are 32-bit registers
stated snlbits and unlbits in different xcliccfg are aliases of each other stated snlbits only present if ssclic is present, unlbits only present if suclic is present

pull for issue #322 cleanup xnlbits text

---

clic.adoc

for issue #333
xinhv is only useful to the exception handler and the interrupt handler shouldn’t really see it.

inhv definition change

---

clic.adoc

memory map clarification for issue #351
smclicconfig was changed from 1B to using 4B so memory map reserved areas need to be updated.  tried to make Ssclic and Suclic match Smclic memory map documentation.

Clarify/Fix Smclic Ssclic Suclic memory map reserved areas

---

clic.adoc

For issue #345, add State enable text similar to that found in Zcmt spec for JVT CSR (although JVT CSR access causes an illegal instruction trap instead of ignoring writes and returning 0 on reads.

adding Smstateen extension text to s-mode clic CSRs

---

clic.adoc

for issue #307, combined two descriptions of NUM_INTERRUPT in the parameters section to a single description.

cleanup NUM_INTERRUPT in parameters section

---

clic.adoc

update spec as discussed in issue #303

clarify CLIC-only CSR behavior when switching CLIC->CLINT->CLIC

---

clic.adoc

For issue #308, allows using CSRRS mnxti to compare valule in rs1 against clic.level instead of mcause.pil which could have been modified by pre-emption.  (replaces pull #343)

add csrrs mnxti behavior

---

clic.adoc

for issue #367, clarify that clicintip behavior is independent of clicintie.

clarification of clicintie/ip edge-trigger interaction

---

clic.adoc

for issue #314 
added note that software may choose to avoid unnecessary context save/restore in hardware-vector handlers by checking mcause.mpil

change xnxti to also return SHV trap-handler entries

---

clic.adoc

Add an additional control bit to allow nxti writes to also signal trigger events.

for issue #371 - nxti behavior on signaling triggers

---

clic.adoc

Since switching from CLINT to CLIC modes already requires xpil in all privilege modes to be zeroed, it follows that they should also just be reset if starting in CLIC mode.

add xcause.xpil fields to mandatory reset state

---

clic.adoc

Separated software interface from CLIC parameters that describe the number of implemented bits.  As described in issues #158, #171, #226, implementations may wish to optimize clicintattr.mode/clicintctl behavior.  This change adds a parameter that specifies the WARL values of clicintctl so implementations have more freedom in how they implement clicintattr.mode/clicintctl and do not have to depend on CLICINTCTLBITS restrictions.

update CLICINTCTLBITS parameter description

---

clic.adoc

for issue #391 - assignment of miselect/siselect range for CLIC ARC allocated indirect CSR numbers 0x1000-0x14A0 for the new CSRs, which keeps this large allocation outside of the lower 12b space.

for issue #391 - assignment of miselect/siselect range for CLIC

---

src/clic.adoc

THe idea is to move any chapter relative to ABI to Appendix

Make some reorganizations in the chapter.

---

src/clic.adoc

Note that the CLIC spec in all but one location was assuming masking for only the IALIGN=16 case. In that one location, it said:
`Note, next_pc is passed to fetch unit which will ignore 1 or 2 LSBs depending to IALIGN, so the masking is not shown above.`.
So, the CLIC spec already assumed the masking/ignoring of 1 or 2 LSBs is a function of IALIGN so with this PR, it now says that consistently and more clearly.

issue #411 - Clarify that smclicshv ignores 1 or 2 LSBs of vector table entry (depending on IALIGN)

---

src/clic.adoc
src/images/wavedrom/clicintattr.edn
src/images/wavedrom/clicintattri.edn
src/images/wavedrom/clicinttrig.edn
src/images/wavedrom/mcliccfg.edn
src/images/wavedrom/scliccfg.edn
src/images/wavedrom/xtvec.edn

I've added several register definitions as diagrams and removed the text based descriptions.  If additional register diagrams are required, please open a new issue and assign to me.

414 move register layout definitions into wavedrom

---

src/aia_clic_extension.adoc

Tried to separate CLIC spec into feature categories.  AIA already has a priority method so I removed the ability of clicintctl to represent a mix of level and priority.  clicintctl was renamed clicintlvl.  I also moved to the ideleg method of assigning privilege modes to interrupts.  With these changes, CLIC parameters was simplified and smclicconfig was rendered unnecessary.  Since clicintlvl only impacts the current privilege mode and CSRs mip/mie are mirrors of the lower 64 interrupts, there no longer appears that there is a need to require all priv modes are CLIC or all priv modes are CLINT.

attempt at creating a AIA clic extension

---

src/clic.adoc

for issue #471.  WFMI proposal was created but never got past draft form.  removing from clic spec.

remove reference to wfmi

---

src/clic.adoc

closes #496, closes #486
adds s-mode access to clicintlvl using siselect and sireg, added to ssclic section.

update to ssclic clicintlvl

---

src/clic.adoc

For issue #470.  clean up and try to be more precise with interrupt preemption text.  updated the preemption table since e was not defined.

clean up redundancy in description of interrupt preemption

---

src/clic.adoc

Adding the necessary registers to make the increase work.
I would also suggest we address the prio/level topic as part of this PR, but I will leave this a separate topic for now.

522 add mechanism analogous to claimi for sw vectored interrupts

---

src/images/wavedrom/clicintattr.edn
src/images/wavedrom/clicintattri.edn

Closes issue #527
remove mode from clicintattr (now using ideleg) and removing trigshv because it isn't defined anywhere in the spec.

Update clicintattr.edn for issue #527

---

src/clic.adoc
src/images/wavedrom/clicintattr.edn
src/images/wavedrom/clicintattri.edn

- Currently there is no known use-case for selective hardware vectoring
- All known use-cases are either full SW or full HW vectoring
- There are promising alternative proposals in case selective hardware vectoring is desired

Removing selective hardware vectoring
